image: alpine
before_script:
  - ./bootstrap.sh
  - eval `ssh-agent -s` && ssh-add
  - bin/buildout -N
tests:
  script:
    -  bin/py.test openprocurement/frameworkagreement/cfaua/tests --cov=openprocurement.frameworkagreement.cfaua
