image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
tests:
  script:
    - bin/py.test openprocurement/tender/cfaselectionua/tests/ --cov=openprocurement.tender.cfaselectionua