image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
stages:
  - test

test_sanbox_true:
  stage: test
  script:
    - SANDBOX_MODE=True
    - bin/py.test ./src/openprocurement/api/tests/ --cov=openprocurement.a
test_sanbox_not_true:
  stage: test
  script:
    - SANDBOX_MODE=
    - bin/py.test ./src/openprocurement/api/tests/ --cov=openprocurement.a
