image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
stages:
  - test

test_sanbox_true:
  stage: test
  variables:
    SANDBOX_MODE: 'True'
  script:
    - bin/py.test ./openprocurement/agreement/cfaua/tests/


test_sanbox_not_true:
  stage: test
  variables:
    SANDBOX_MODE: ''
  script:
    - bin/py.test ./openprocurement/agreement/cfaua/tests/