image: alpine
before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
stages:
  - test

test_sanbox_true:
  stage: test
#  varibles:
#    SANDBOX_MODE: 'True'
  script:
    - echo $SANDBOX_MODE
    - bin/py.test ./src/openprocurement/api/tests/ --cov=openprocurement.api


test_sanbox_not_true:
  stage: test
#  varibles:
#    SANDBOX_MODE: ''

  script:
    - echo $SANDBOX_MODE
    - bin/py.test ./src/openprocurement/api/tests/ --cov=openprocurement.api
